# Site settings
title: X+1's Blog
SEOTitle: 叮当猫的麻袋 | X+1's Blog
header-img: img/about-bg-walle.jpg
email: master@kellyxu.com
description: "All about time and space."
keyword: "kellyxu"
url: "http://kellyxu.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    kellyxu-com
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
#disqus_username: hux

# Netease settings
#netease_comment: false

# Analytics settings
# Baidu Analytics
ba_track_id: kellyxu.com

# Google Analytics
ga_track_id: 'UA-164480924-1'            # Format: UA-xxxxxx-xx
ga_domain: kellyxu.com

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "All about time and space"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Serve Command Options
#encoding: utf-8 # Set the encoding of files by name (only available for Ruby 1.9 or later). The default value is utf-8
#timezone: Asia/Shanghai # Set the time zone for site generation. This sets the TZ environment variable, which Ruby uses to handle time and date creation and manipulation.
port: 3333 # Listen on the given port.
host:  127.0.0.1 # Listen at the given hostname.
# host:  0.0.0.0 # Listen at the given hostname.
livereload: false # Reload a page automatically on the browser when its content is edited.
detach: false # Detach the server from the terminal.

# Friends
friends: [
    {
        title: "锐e空间",
        href: "http://rayspace.cn/"
    }
]
